train: /data/students/juan/train/grocery-item-segmentation-yolo/dataset/images/train
val: /data/students/juan/train/grocery-item-segmentation-yolo/dataset/images/val
nc: 24
names: ['bottled_soda', 'cheese', 'Kitkat', 'coffee', 'condensed_milk', 'Cooking_oil', 'corned beef', 'garlic', 'instant_noodles', 'Ketchup', 'lemon', 'All Purpose Cream', 'Mayonnaise', 'peanut_butter', 'pasta', 'pineapple juice', 'crackers', '18', 'pink_shampoo', '20', 'silverswan', 'toothpaste', 'canned-tuna', 'GreenCross Ethyl Alcohol']
augmentation:
  mosaic: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.373
  translate: 0.45
  scale: 0.5
  shear: 0.3
  flipud: 0.01
  fliplr: 0.5
  blur: 0.1
