train: /data/students/juan/train/grocery-item-segmentation-yolo/dataset/images/train
val: /data/students/juan/train/grocery-item-segmentation-yolo/dataset/images/val
nc: 22
names: ['bottled_soda', 'cheese', 'Kitkat', 'coffee', 'condensed_milk', 'Cooking_oil', 'corned beef', 'garlic', 'instant_noodles', 'lemon', 'Mayonnaise', 'peanut_butter', 'pasta', 'pineapple juice', 'crackers', '18', 'pink_shampoo', '20', 'silverswan', 'toothpaste', 'canned-tuna', 'GreenCross Ethyl Alcohol']
